# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
    CYGWIN_ROOT: $(System.Workfolder)\cygwin
    CYGWIN_CMAKE_LINK: http://cygwin.mirror.constant.com/x86_64/release/cmake/cmake-3.13.1-1.tar.xz
    CYGWIN_MIRROR: http://cygwin.mirror.constant.com

steps:
  - script: |
      choco install cygwin --params="/InstallDir:%CYGWIN_ROOT%"
    displayName: Install Cygwin
  - script: |
      %CYGWIN_ROOT%\cygwinsetup.exe -qnNdO -R "%CYGWIN_ROOT%" -s "%CYGWIN_MIRROR%" -g -P ^
      gcc-fortran,^
      gcc-objc++,^
      gcc-objc,^
      git,^
      gobject-introspection,^
      libarchive13,^
      libboost-devel,^
      libglib2.0-devel,^
      libgtk3-devel,^
      libjsoncpp19,^
      librhash0,^
      libuv1,^
      ninja,^
      python35-pip,^
      vala,^
      wget,^
      zlib-devel
    displayName: Install Dependencies
  - script: |
      %CYGWIN_ROOT%\bin\bash.exe -cl "wget %CYGWIN_CMAKE_LINK% -O cmake.tar.xz"
      %CYGWIN_ROOT%\bin\bash.exe -cl "tar -xf cmake.tar.xz -C /"
    displayName: Manually install CMake 3.13.1
  - script: |
      set BOOST_ROOT=
      set PATH=%CYGWIN_ROOT%\bin;%SYSTEMROOT%\system32
      gradlew.bat tasks
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'sdk'
